-- QUESTIONS (auto-generated id)
INSERT INTO question (category, question_title, option1, option2, option3, option4, right_answer, difficulty_level) VALUES
('Programming', 'What is the output of print(2**3)?', '6', '8', '9', '12', '8', 'Easy'),
('Programming', 'Which of these is not a Python data type?', 'List', 'Tuple', 'Dictionary', 'Tree', 'Tree', 'Easy'),
('Programming', 'What is PEP 8?', 'Python Enhancement Proposal', 'A Python IDE', 'A library', 'An error message', 'Python Enhancement Proposal', 'Medium'),
('Programming', 'How do you start a comment in Python?', '//', '#', '<!--', '/*', '#', 'Easy'),
('Programming', 'What does len() do?', 'Length of value', 'Adds numbers', 'Creates a list', 'Removes item', 'Length of value', 'Easy'),
('Programming', 'Which keyword creates a function?', 'fun', 'define', 'def', 'func', 'def', 'Easy'),
('Programming', 'Which operator for floor division?', '//', '/', '%', '^', '//', 'Medium'),
('Programming', 'How do you create a variable with the floating number 2.8?', 'x = float(2.8)', 'x = 2.8f', 'x := 2.8', 'float x = 2.8', 'x = float(2.8)', 'Medium'),
('Programming', 'Which method adds an item to a list?', 'append()', 'add()', 'push()', 'insert()', 'append()', 'Easy'),
('Programming', "What does 'pass' do?", 'Skips loop', 'Returns 0', 'Does nothing', 'Ends program', 'Does nothing', 'Medium'),

('Programming', 'What is JVM?', 'Java Virtual Machine', 'Java Vendor Machine', 'Java Versatile Method', 'Joint Venture Model', 'Java Virtual Machine', 'Easy'),
('Programming', 'Which is a valid Java identifier?', '2Test', 'test@java', 'Test_2', '@test', 'Test_2', 'Easy'),
('Programming', 'Public static void main(String[] args) is', 'A variable', 'A constructor', 'A method', 'A class', 'A method', 'Medium'),
('Programming', 'How to declare int variable in Java?', 'var i;', 'int i;', 'declare int i;', 'int = i', 'int i;', 'Easy'),
('Programming', 'Which operator compares two values?', '==', '=', '+=', ':=', '==', 'Easy'),
('Programming', 'Java source code extension?', '.jav', '.java', '.class', '.j', '.java', 'Easy'),
('Programming', 'Which collection is synchronized?', 'ArrayList', 'Vector', 'HashMap', 'TreeSet', 'Vector', 'Medium'),
('Programming', 'How to create an object?', 'Object obj = new Object();', 'Object obj();', 'obj = Object();', 'new Object;', 'Object obj = new Object();', 'Medium'),
('Programming', 'Where do you write package statement?', 'After class', 'Before import', 'First line', 'Last line', 'First line', 'Medium'),
('Programming', 'Which is not access modifier?', 'private', 'friend', 'protected', 'public', 'friend', 'Medium'),

('Programming', 'Which is correct variable declaration in JS?', 'var myVar;', 'int myVar;', 'myVar int;', 'declare myVar;', 'var myVar;', 'Easy'),
('Programming', "What does '===' check?", 'Type only', 'Value only', 'Type & Value', 'Reference', 'Type & Value', 'Medium'),
('Programming', 'How to write single-line comment?', '// Comment', '# Comment', '<!-- Comment -->', '/* Comment */', '// Comment', 'Easy'),
('Programming', 'How to output to console?', 'print()', 'echo()', 'console.log()', 'output()', 'console.log()', 'Easy'),
('Programming', 'Which is NOT a JS framework?', 'React', 'Angular', 'Spring', 'Vue', 'Spring', 'Easy'),
('Programming', 'typeof null in JS?', 'object', 'null', 'undefined', 'string', 'object', 'Medium'),
('Programming', "Which gives NaN?", "parseInt('abc')", "'abc'+1", "1+'abc'", "parseInt(1)", "parseInt('abc')", 'Medium'),
('Programming', 'Which creates a function?', 'function f(){}', 'def f(){}', 'fun f(){}', 'create f(){}', 'function f(){}', 'Easy'),
('Programming', 'How to select by id in DOM?', 'getElementById', 'querySelectorAll', 'getElementsByClassName', 'getById', 'getElementById', 'Medium'),
('Programming', 'How to convert string to integer?', 'parseInt()', 'Number()', 'Both A & B', 'parseIntInt()', 'Both A & B', 'Medium'),

('Programming', 'C file extension?', '.c', '.cpp', '.java', '.h', '.c', 'Easy'),
('Programming', 'Main function in C?', 'start()', 'begin()', 'main()', 'init()', 'main()', 'Easy'),
('Programming', 'Which is valid printf usage?', "printf('Hello');", 'printf(\"Hello\");', "print('Hello');", 'print(\"Hello\");', 'printf(\"Hello\");', 'Medium'),
('Programming', 'Which format specifier for int?', '%d', '%i', '%f', '%s', '%d', 'Easy'),
('Programming', 'Which is NOT a loop?', 'for', 'while', 'repeat', 'do-while', 'repeat', 'Medium'),
('Programming', 'Declare char array?', 'char str[10];', 'str char[10];', 'array char str[10];', 'char arr(10);', 'char str[10];', 'Medium'),
('Programming', 'End statement symbol in C?', ';', '.', ':', '/', ';', 'Easy'),
('Programming', 'How to input integer?', "scanf('%d',&x);", 'read x;', 'input(x);', 'scan(x);', "scanf('%d',&x);", 'Medium'),
('Programming', 'C does not have?', 'Pointers', 'Classes', 'Functions', 'Arrays', 'Classes', 'Medium'),
('Programming', 'Standard header for I/O?', 'stdio.h', 'conio.h', 'io.h', 'stdlib.h', 'stdio.h', 'Medium'),

('Programming', 'What does SQL stand for?', 'Structured Question List', 'Structured Query Language', 'Statement Query Language', 'Simple Query Language', 'Structured Query Language', 'Easy'),
('Programming', 'Which is NOT SQL command?', 'SELECT', 'DELETE', 'UPDATE', 'CHANGE', 'CHANGE', 'Easy'),
('Programming', 'Which wildcard for any characters?', '$', '%', '_', '*', '%', 'Easy'),
('Programming', 'Which statement adds data?', 'INSERT', 'JOIN', 'UPDATE', 'SELECT', 'INSERT', 'Easy'),
('Programming', 'Primary key can be?', 'Duplicate', 'Null', 'Unique', 'None', 'Unique', 'Easy'),
('Programming', 'Which is aggregate function?', 'COUNT', 'WHERE', 'JOIN', 'UPDATE', 'COUNT', 'Medium'),
('Programming', 'Altering table means?', 'Delete rows', 'Add columns', 'Change table structure', 'Change DB', 'Change table structure', 'Medium'),
('Programming', 'How to sort result set?', 'ORDER BY', 'GROUP BY', 'SORT BY', 'ORDER', 'ORDER BY', 'Medium'),
('Programming', 'Which returns unique values?', 'SELECT DISTINCT', 'SELECT UNIQUE', 'SELECT ONLY', 'SELECT ONE', 'SELECT DISTINCT', 'Medium'),
('Programming', 'Which is DDL statement?', 'INSERT', 'UPDATE', 'CREATE', 'ALTER', 'CREATE', 'Medium');

